name: generate-snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ShaazKazi
          outputs: |
            dist/github-snake.svg?color_snake=%2339FF14&color_dots=%230D1117,%230B3D0B,%23146B14,%231FA31F,%2339FF14
            dist/github-snake-dark.svg?color_snake=%2339FF14&color_dots=%230D1117,%230B3D0B,%23146B14,%231FA31F,%2339FF14

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
